#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType specie
wmake $makeType reactionThermo
wmake $makeType chemistryModel
wmake $makeType radiationModels
