/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2013-2013 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Typedefs
    Foam::thermoPhysicsTypes

Description
    Type definitions for thermo-physics models

\*---------------------------------------------------------------------------*/

#ifndef thermoPhysicsTypes_H
#define thermoPhysicsTypes_H

#include "specie.H"
#include "PRVTA.H"
#include "PengRobinsonGas.H"
#include "perfectGas.H"
#include "hPolynomialThermo.H"
#include "janafThermo.H"
#include "janafRealThermo.H"
#include "CpFromEoSThermo.H"
#include "sensibleEnthalpy.H"
#include "sensibleInternalEnergy.H"
#include "thermo.H"
#include "chungTransport.H"
#include "sutherlandTransport.H"
#include "sutherlandRealTransport.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{
    // thermo physics types based on sensibleEnthalpy
    typedef
    sutherlandRealTransport //chungTransport
    <
	species::thermo
	<
	    janafRealThermo
	    <
		PRVTA<specie>
	    >,
	    sensibleEnthalpy
	>
    > PRVTAPhysics;

    typedef
    sutherlandTransport
    <
	species::thermo
	<
	    janafThermo
	    <
		PRVTA<specie> //perfectGas<specie>
	    >,
	    sensibleEnthalpy
	>
    > idealGasPhysics;

}

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
