#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake
wmake rhoReactingFoam
wmake rhoReactingModdedPISOFoam
wmake rhoReactingBuoyantFoam
wmake LTSReactingFoam

# ----------------------------------------------------------------- end-of-file
